version: '3'

services:

  app:
    build:
      context: ../build
      dockerfile: ./Dockerfile
    env_file: .env
    restart: always
    depends_on:
      - postgres
    ports:
      - ${WEB_SERVER_PORT}:${WEB_SERVER_PORT}
      - ${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}
      - ${GRAPHQL_SERVER_PORT}:${GRAPHQL_SERVER_PORT}
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ../data/postgres/:/var/lib/postgresql/data/
